#!/bin/bash

VAR="$HOME/.config/i3blocks/blocklets/.rec"
RECORDING="$(cat $VAR)"

function setup {
	touch $VAR
	echo 0 > $VAR
}

function displayAudioInfo {
	if [[ "$RECORDING" = 0 ]]; then
		echo "⏺ AUDIO"
	fi
}

function displayRecordingInfo {
	if [[ "$RECORDING" = 0 ]]; then
		echo "⏺ REC"
	fi
}

# Toggle the variable so the state changes each time this is executed
# If it's on, it will be off on the next execution, and vice versa.
function toggle {
	if [[ $RECORDING = 0 ]]; then
		echo 1 > $VAR
	elif [[ $RECORDING = 1 ]]; then
		echo 0 > $VAR
	fi
}

[[ ! -f $VAR ]] && setup

while test $# -gt 0; do
	case "$1" in
		--audio)
			displayAudioInfo
			toggle
			break
			;;
		--all)
			displayRecordingInfo
			toggle
			break
			;;
	esac
done
