#!/bin/sh

title="$(xdotool getactivewindow getwindowname)"

function start {
	ffmpeg -y \
	-f pulse \
	-i default \
	-c:a flac \
	"$HOME/Videos/$title/$title $(date +"%d-%m-%Y - %T")".flac
}

function stop {
	[[ -n "$(pidof ffmpeg)" ]] && pkill -SIGINT ffmpeg && exit 0
}

if [[ -z "$(pidof ffmpeg)" ]]; then
	
	# I had a check here to detect whether or not the
	# directory was already created, but it gave me problems
	# with some windows, inverting the logic and not creating
	# the directory if it did not exist.
	mkdir "$HOME/Videos/$title"
	
	start
else
	stop
fi
